version: "3" 
services:
    db:
        image: postgres:13-alpine
        container_name: pg
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data/pgdata
            - ./createdb.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=test_user
            - POSTGRES_PASSWORD=qwerty
            - POSTGRES_DB=appdb
            - PGDATA=/var/lib/postgresql/data/pgdata
        restart: always
    rediscache:
        image: redis:6.2.1-alpine
        ports:
            - "6379:6379"
        command: redis-server --requirepass lol123qqz
        volumes:
            - $PWD/redis-data:/var/lib/redis
            - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
        restart: always
    app:
        build: server/
        container_name: app
        ports:
            - 3000:3000
        environment:
            PG_HOST: db
            REDIS_HOST: rediscache
            REDIS_PASSWORD: lol123qqz
        restart: always
        links:
            - db
            - rediscache
        ports:
            - 3000:3000
        depends_on:
            - db
            - rediscache
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
        links:
            - app
        depends_on:
            - app
